[//]: # (https://stackoverflow.com/questions/4823468/comments-in-markdown)
[//]: # remote_theme: pages-themes/slate@v0.2.0
[//]: # remote_theme: pages-themes/minimal@v0.2.0
[//]: # remote_theme: pages-themes/cayman@v0.2.0
[//]: # remote_theme: pages-themes/dinky@v0.2.0
[//]: # remote_theme: pages-themes/modernist@v0.2.0
[//]: # title: [<span style="font-size:0.8em;">Патофизиология сердца и сосудов</span>]
[//]: #title: [<img src="./k.png" alt="logo" />]

[//]: # title: [Патофизиология сердечно-сосудистой системы]
[//]: # title: [<span style="font-size:1.7em;">Патофизиология сердца и сосудов</span>]
