[//]: # remote_theme: pages-themes/minimal@v0.2.0
[//]: # remote_theme: pages-themes/cayman@v0.2.0
[//]: # remote_theme: pages-themes/dinky@v0.2.0
[//]: # remote_theme: pages-themes/modernist@v0.2.0

title: [<img src="./лого.png" alt="logo" />]
 



